# Generated by Django 4.2.23 on 2025-09-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_facebook_profile_instagram_profile_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentidea',
            name='input_prompt',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contentidea',
            name='post_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='contentidea',
            name='tone',
            field=models.CharField(choices=[('informative', 'Informative'), ('funny', 'Funny'), ('professional', 'Professional')], default='informative', max_length=20),
        ),
    ]
