# Generated by Django 4.2.23 on 2025-09-27 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_contentidea_input_prompt_contentidea_post_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaupload',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.CreateModel(
            name='TTSAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='tts/')),
                ('script_text', models.TextField()),
                ('voice', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contentidea')),
                ('media', models.ManyToManyField(to='core.mediaupload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
